# Generated by Django 3.0.7 on 2020-07-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyportfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationAndBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
