# Generated by Django 3.0.7 on 2020-07-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyportfolio', '0002_auto_20200724_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificationandbook',
            old_name='titre',
            new_name='title',
        ),
    ]
